export interface Patient {
    id?: number;          // Optional because it’s auto-generated by DB
    name: string;
    age: number;
    gender: string;  // You can limit gender options like this
    address: string;
    contact: string;      // Phone number as string (to support formatting, +country codes)
    email: string;
    createdAt: string;    // ISO date string format, e.g. '2025-05-20T12:34:56Z'
  }
  